"""
Tests for src/judgment/prompt.py::build_messages -- specifically the
`retrieved_context` parameter added for Retrieval v1 (see
engine/decisions.md "Retrieval", src/retrieval/engine.py). Pure function
of strings, no mocking needed.
"""

from __future__ import annotations

from src.judgment.prompt import build_messages


def test_build_messages_omits_retrieved_context_section_when_empty():
    _, messages = build_messages("{}", [], retrieved_context="")
    assert "Retrieved Context" not in messages[0]["content"]


def test_build_messages_includes_retrieved_context_section_when_present():
    _, messages = build_messages(
        "{}", [], retrieved_context="Known pattern: reopens closed decisions."
    )
    content = messages[0]["content"]
    assert "Retrieved Context (from past Journeys, not generated by you):" in content
    assert "Known pattern: reopens closed decisions." in content


def test_build_messages_defaults_retrieved_context_to_empty_string():
    """Every existing caller that doesn't pass retrieved_context at all
    (every test predating Retrieval) must still work unchanged."""
    _, messages = build_messages("{}", [])
    assert "Retrieved Context" not in messages[0]["content"]
